version: '3.8'
services:
  mysql:
    image: mysql:8.0.41
    container_name: mysql-agro-app
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: agro_app
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: